AppBundle\Entity\posts:
    type: entity
    repositoryClass: AppBundle\Repository\postsRepository
    table: posts
    id:
        id:
            type: integer
            nullable: false
            options:
                unsigned: false
            id: true
            generator:
                strategy: IDENTITY
    fields:
        title:
            type: string
            nullable: false
            length: 100
            options:
                fixed: false
        content:
            type: text
            nullable: false
            length: null
            options:
                fixed: false
    lifecycleCallbacks: {  }
